[package]
name = "bevy_erm_sqlite"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "*", default-features = false, features = ["bevy_color"] }
bevy_erm = { git = "https://github.com/thorbenbaerentson/bevy_erm" }
rusqlite = { version = "0.34.0", features = ["bundled"] }