[package]
name = "bevy_erm_sqlite"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "*", default-features = true }
bevy_erm = { path = "../bevy_erm" }
rusqlite = { version = "0.34.0", features = ["bundled"] }